version: "3.3"

services:
    
  spincastone:
    image: spincastone   
    build: ./spincastone
    container_name: spincastone
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    ports:
      - '44419:44419'
    volumes:
      - /opt/spincastone/logs/:/opt/spincastone/logs
    networks:
      - socnet
    
  
  
   

networks:
  socnet:
    driver: bridge
